### ISSUE TITLE
Upgrade `deep-extend` to avoid `npm audit` security vulnerability 

### ISSUE THREAD

**Issue by ehmicky** [pateketrueke/deref#13]
This package is marked as vulnerable by `npm audit` because of a dependency on this [deep-extend vulnerability](https://nodesecurity.io/advisories/612). 

It can be fixed by removing your `package-lock.json` then running `npm install` again.

Note that `json-schema-faker` might need to update its `package-lock.json` as well after this.

**Comment by ehmicky** [comment]
PR in #14

**Comment by pateketrueke** [comment]
Thank you!

I'll release a new version soon.
