### ISSUE TITLE
low severity vulnerabilitiy

### ISSUE THREAD

**Issue by Nephos** [pateketrueke/deref#15]
Hello,

https://nodesecurity.io/advisories/612

**Comment by chrislukkk** [comment]
It seems deep-extend package reference has been updated to 0.5.1 in master.
@pateketrueke any ETA on publishing this as a new version of deref to get ride of the vulnerability?

**Comment by pateketrueke** [comment]
This is good news, thank you!

Released: `deref@0.7.4`
