### ISSUE TITLE
deref@0.7.4 cannot be installed from NPM

### ISSUE THREAD

**Issue by RoobinGood** [pateketrueke/deref#16]
I can't install latest version of `deref`:

```
> npm i deref
npm ERR! fetch failed https://registry.npmjs.org/deref/-/deref-0.7.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/deref/-/deref-0.7.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/deref/-/deref-0.7.4.tgz
npm ERR! Linux 4.15.0-30-generic
npm ERR! argv "/home/anatoly/.nvm/versions/node/v4.9.1/bin/node" "/home/anatoly/.nvm/versions/node/v4.9.1/bin/npm" "i" "deref"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11

npm ERR! fetch failed with status code 404
```

Issue reproduced with npm@5.6.0 because problem with registry - there is no package tarball at https://registry.npmjs.org/deref/-/deref-0.7.4.tgz

I think it can be connected with yesterday NPM issue - https://status.npmjs.org/incidents/h7sbpn9sbkgc

Can you please publish current version again as 0.7.5?

**Comment by gleme** [comment]
Same here, can't install loopback-cli
![image](https://user-images.githubusercontent.com/12916704/44789896-30517180-ab74-11e8-9860-c9fc12c714d9.png)

**Comment by laspinacristian** [comment]
Same issue for me. 
actually defer is a nested dep for loopback-cli. Do you know how can i tell npm to install 0.7.3 as a dependency instead of 0.74?

**Comment by pateketrueke** [comment]
Thank you guys, republished: https://registry.npmjs.org/deref/-/deref-0.7.5.tgz 👍

**Comment by gleme** [comment]
thanks a lot guys!
