### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jo** [pateketrueke/deref#3]
I use [json-schema-faker](https://github.com/pateketrueke/json-schema-faker) for generating test data in a project which also includes [z-schema](https://github.com/zaggino/z-schema) for validation.

When using an already "compiled" schema it hangs:

``` sh
RangeError: Maximum call stack size exceeded
```

A possible fix is to prevent cloning of private properties (which are inserted during the compile process), marked with `__$`.
After
[deref/lib/util/clone-obj.js#19](https://github.com/pateketrueke/deref/blob/master/lib/util/clone-obj.js#L19)
insert the following statement:

``` js
if (key.slice(0, 3) === '__$') {
  return;
}
```

**Comment by jo** [comment]
a292d0622f0f24bd6f68425bd48260af96ccc894 contains the possible fix described above.

**Comment by pateketrueke** [comment]
Seems like z-schema is adding its own properties, in my tests [I've cloned everything](https://github.com/pateketrueke/deref/blob/master/spec/helpers.coffee#L29) due that.

Are you reusing the same object between `z-schema` and `json-schema-faker`?

I think this is possible (and valid):

``` json
{
  "type": "object",
  "properties": {
    "__$": { "type": "string" }
  },
  "required": ["__$"]
}
```

I don't like fixing just for indirection, if `z-schema` is mutating your schema is not your issue.

The behavior of `deref` is completely agnostic of that, if you pass a circular reference it will hang.

**Comment by jo** [comment]
I see your point, the solution I mentioned was a hack.

And I indeed share the same object between z-schema and json-schema-faker. Using a cloned object for validation has fixed my issue.

Thank you!
